# Generated by Django 4.2 on 2023-04-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PacotePromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomepacotepromocional', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('marcada', models.BooleanField()),
                ('picture', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoPacotePromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_pacotes_promocionais', models.ForeignKey(blank=True, db_column='fk_id_pacotes_promocionais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_trabalho_final.pacotepromocional')),
                ('fk_id_servico', models.ForeignKey(blank=True, db_column='fk_id_servico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_trabalho_final.servico')),
            ],
        ),
    ]
