# Generated by Django 4.2 on 2023-04-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_trabalho_final', '0003_rename_comentarios_comentario_rename_images_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
